name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build_and_release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          New-Item -ItemType Directory -Force -Path build/assets

      - name: Check for updates
        id: check_updates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python check_versions.py

      - name: Set Build Date
        if: github.event_name != 'schedule' || env.UPDATE_NEEDED == 'true'
        run: |
          $date = Get-Date -Format 'yyyy-MM-dd'
          echo "BUILD_DATE=$date" >> $env:GITHUB_ENV

      - name: Build Edge
        if: github.event_name != 'schedule' || env.UPDATE_NEEDED == 'true'
        run: |
          python run.py
          $version = Get-Content build/release/Edge/version.txt
          echo "EDGE_VERSION=$version" >> $env:GITHUB_ENV
          $archiveName = "Edge_Portable_Win64_${{ env.BUILD_DATE }}.7z"
          7z a -t7z -mx=9 "build/assets/$archiveName" build/release/*

      - name: Upload Artifacts
        if: github.event_name != 'schedule' || env.UPDATE_NEEDED == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: Edge-Portable-Builds
          path: build/assets/*.7z
          retention-days: 15

      - name: Update Existing Release
        if: (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') && env.UPDATE_NEEDED == 'true' && env.CREATE_NEW_RELEASE == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python update_release.py

      - name: Upload Assets to Existing Release
        if: (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') && env.UPDATE_NEEDED == 'true' && env.CREATE_NEW_RELEASE == 'false'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: build/assets/*.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create New Release
        if: (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') && env.UPDATE_NEEDED == 'true' && env.CREATE_NEW_RELEASE == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.EDGE_VERSION }}
          name: Edge Portable v${{ env.EDGE_VERSION }}
          body: |
            自动构建的 Microsoft Edge 便携版
            解压后即可使用，数据文件存储在同级文件夹下
            官方发行说明 / Official Release Notes: [microsoft-edge-relnote-stable-channel](https://learn.microsoft.com/zh-cn/deployedge/microsoft-edge-release-notes)
            
            构建时间: ${{ env.BUILD_DATE }}
            Edge 版本: ${{ env.EDGE_VERSION }}
          files: build/assets/*.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete Older Releases
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' && env.UPDATE_NEEDED == 'true')
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 10
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
