name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  portable:
    permissions:
      contents: write
    uses: Piracola/ChromiumPortable/.github/workflows/portable-browser.yml@v1.1
    with:
      builder-repository: Piracola/ChromiumPortable
      builder-ref: v1.1
      config: browser.json
      target: edge_stable
      artifact-name: Edge-Portable-Build
