name: build

on:
  workflow_dispatch:
    inputs:
      builder_ref:
        description: ChromiumPortable ref to use.
        required: false
        default: main
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  portable:
    concurrency:
      group: edge-portable-build
      cancel-in-progress: false
    permissions:
      contents: write
    uses: Piracola/ChromiumPortable/.github/workflows/portable-browser.yml@main
    with:
      builder-repository: Piracola/ChromiumPortable
      builder-ref: ${{ github.event.inputs.builder_ref || 'main' }}
      config: browser.json
      target: edge_stable
      artifact-name: Edge-Portable-Build
